/*
 * In-Game Advertising API
 *
 * Simple API for in-game market campaigns
 *
 * API version: 1.0.0
 * Contact: maessoumi.dev@gmail.com.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Ad struct {

	FileType string `json:"fileType,omitempty"`

	Ref string `json:"ref,omitempty"`

	Size int32 `json:"size,omitempty"`

	Adult bool `json:"adult,omitempty"`

	Children bool `json:"children,omitempty"`
}
