/*
 * In-Game Advertising API
 *
 * Simple API for in-game market campaigns
 *
 * API version: 1.0.0
 * Contact: maessoumi.dev@gmail.com.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CampaignAd struct {

	Id int32 `json:"id,omitempty"`

	AdId int32 `json:"adId"`

	CampaignId int32 `json:"campaignId"`

	Deactivated bool `json:"deactivated,omitempty"`
}
