/*
 * In-Game Advertising API
 *
 * Simple API for in-game market campaigns
 *
 * API version: 1.0.0
 * Contact: maessoumi.dev@gmail.com.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Client struct {

	Id int32 `json:"id,omitempty"`

	ParentId int32 `json:"parentId,omitempty"`

	Name string `json:"name,omitempty"`

	Industry string `json:"industry,omitempty"`

	Adult bool `json:"adult,omitempty"`

	Children bool `json:"children,omitempty"`

	Tier int32 `json:"tier,omitempty"`

	CurrentClient bool `json:"currentClient,omitempty"`
}
