/*
 * In-Game Advertising API
 *
 * Simple API for in-game market campaigns
 *
 * API version: 1.0.0
 * Contact: maessoumi.dev@gmail.com.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Game struct {

	Id int32 `json:"id,omitempty"`

	Title string `json:"title,omitempty"`

	CompanyId int32 `json:"companyId,omitempty"`

	Release string `json:"release,omitempty"`
}
