/*
 * In-Game Advertising API
 *
 * Simple API for in-game market campaigns
 *
 * API version: 1.0.0
 * Contact: maessoumi.dev@gmail.com.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/MAESSOUMIDEV/market-campaign-simple/1.0.0/",
		Index,
	},

	Route{
		"AddAd",
		strings.ToUpper("Post"),
		"/MAESSOUMIDEV/market-campaign-simple/1.0.0/ad",
		AddAd,
	},

	Route{
		"AddCampaign",
		strings.ToUpper("Post"),
		"/MAESSOUMIDEV/market-campaign-simple/1.0.0/campaign",
		AddCampaign,
	},

	Route{
		"AddCampaignAd",
		strings.ToUpper("Post"),
		"/MAESSOUMIDEV/market-campaign-simple/1.0.0/campaignad",
		AddCampaignAd,
	},

	Route{
		"SearchAds",
		strings.ToUpper("Get"),
		"/MAESSOUMIDEV/market-campaign-simple/1.0.0/ad",
		SearchAds,
	},

	Route{
		"SearchCampaignAds",
		strings.ToUpper("Get"),
		"/MAESSOUMIDEV/market-campaign-simple/1.0.0/campaignad",
		SearchCampaignAds,
	},

	Route{
		"SearchCampaigns",
		strings.ToUpper("Get"),
		"/MAESSOUMIDEV/market-campaign-simple/1.0.0/campaign",
		SearchCampaigns,
	},

	Route{
		"AddAd",
		strings.ToUpper("Post"),
		"/MAESSOUMIDEV/market-campaign-simple/1.0.0/ad",
		AddAd,
	},

	Route{
		"AddCampaign",
		strings.ToUpper("Post"),
		"/MAESSOUMIDEV/market-campaign-simple/1.0.0/campaign",
		AddCampaign,
	},

	Route{
		"AddCampaignAd",
		strings.ToUpper("Post"),
		"/MAESSOUMIDEV/market-campaign-simple/1.0.0/campaignad",
		AddCampaignAd,
	},

	Route{
		"SearchAds",
		strings.ToUpper("Get"),
		"/MAESSOUMIDEV/market-campaign-simple/1.0.0/ad",
		SearchAds,
	},

	Route{
		"SearchCampaignAds",
		strings.ToUpper("Get"),
		"/MAESSOUMIDEV/market-campaign-simple/1.0.0/campaignad",
		SearchCampaignAds,
	},

	Route{
		"SearchCampaigns",
		strings.ToUpper("Get"),
		"/MAESSOUMIDEV/market-campaign-simple/1.0.0/campaign",
		SearchCampaigns,
	},

	Route{
		"AddAd",
		strings.ToUpper("Post"),
		"/MAESSOUMIDEV/market-campaign-simple/1.0.0/ad",
		AddAd,
	},

	Route{
		"AddCampaign",
		strings.ToUpper("Post"),
		"/MAESSOUMIDEV/market-campaign-simple/1.0.0/campaign",
		AddCampaign,
	},

	Route{
		"AddCampaignAd",
		strings.ToUpper("Post"),
		"/MAESSOUMIDEV/market-campaign-simple/1.0.0/campaignad",
		AddCampaignAd,
	},

	Route{
		"SearchAds",
		strings.ToUpper("Get"),
		"/MAESSOUMIDEV/market-campaign-simple/1.0.0/ad",
		SearchAds,
	},

	Route{
		"SearchCampaignAds",
		strings.ToUpper("Get"),
		"/MAESSOUMIDEV/market-campaign-simple/1.0.0/campaignad",
		SearchCampaignAds,
	},

	Route{
		"SearchCampaigns",
		strings.ToUpper("Get"),
		"/MAESSOUMIDEV/market-campaign-simple/1.0.0/campaign",
		SearchCampaigns,
	},
}
